### ISSUE TITLE
Convert all text messages to JSON-formatted messages

### ISSUE THREAD

**Issue by bilthon** [MostroP2P/mostro-core#4]
Mostro will currently send some text messages to the clients, these messages are defined [here](https://github.com/MostroP2P/mostro/blob/main/src/messages.rs). This proposal aims to extend the current mostro protocol described [here](https://mostro.network/order-flow/) and replace all text messages by JSON objects.

The motivation for this extension is that:

1. Simplifies the client-side handling of messages. If a client wants to apply specific formatting rules, say a shortened version of npubs for mobile screens for instance, having the important pieces of information already as attributes of an object is better than a plain message that we must parse. Same thing applies for localization.

2. Simplifies mostro a bit by lifting this presentation-layer concern from it.

Here I propose the conversion of 3 text messages that are already implemented in the [mostro-web](https://github.com/MostroP2P/mostro-web) client. As such it would be ideal if mostro-core also implemented these messages in the same format. New issues can be created for the other messages.

### Invoice Accepted
Currently implemented by the [buyer_took_order](https://github.com/MostroP2P/mostro/blob/a5dba7d5e4a93c4d1b7020d5d789e0dfd3f4d30f/src/messages.rs#L21) function.
 A new action, called `InvoiceAccepted` is proposed for this message. Here's an example of the current text message:

```text
🧌 Order Id: 6d3249ba-e5ec-4b7b-afa2-7d9b2ccab0dc

        npub1kk30z9gus7xk3kf3m8zxh9paw4ngw023he9037y2jd7y7msfvvdskj8e60 has taken your order and wants to buy your sats. Get in touch and tell him/her how to send you PEN 420 through IBK.

        Once you verify you have received the full amount you have to release the sats
```

And this is an example of how the proposed JSON payload would look like:

```json
{
  "version": 0,
  "action": "InvoiceAccepted",
  "order_id": "6d3249ba-e5ec-4b7b-afa2-7d9b2ccab0dc",
  "content": {
    "InvoiceAccepted": {
        "order_id": "f6204501-6868-4919-8b8b-7b15a7746e4f",
        "buyer": "npub1kk30z9gus7xk3kf3m8zxh9paw4ngw023he9037y2jd7y7msfvvdskj8e60",
        "fiat_amount": 420,
        "fiat_code": "PEN",
        "payment_method": "IBK"    
    }
  }
}
```

### Fiat Sent
Currently implemented by the [buyer_sentfiat](https://github.com/MostroP2P/mostro/blob/a5dba7d5e4a93c4d1b7020d5d789e0dfd3f4d30f/src/messages.rs#L41) function, an example of the current text message is the following:

```text
🧌 Order Id: 0c0e9936-4c21-47a5-87c1-01503a313003

    npub1kk30z9gus7xk3kf3m8zxh9paw4ngw023he9037y2jd7y7msfvvdskj8e60 has informed that already sent you the fiat money, once you confirmed you received it, please release funds. You will not be able to create another order until you release funds.
```

The proposed JSON payload would look like this:
```json
{
  "version": 0,
  "action": "FiatSent",
  "order_id": "6d3249ba-e5ec-4b7b-afa2-7d9b2ccab0dc",
  "content": {
    "Peer": {
        "pubkey": "npub1kk30z9gus7xk3kf3m8zxh9paw4ngw023he9037y2jd7y7msfvvdskj8e60",
    }
  }
}
```

### Sale completed

Currently implemented by the [sell_success](https://github.com/MostroP2P/mostro/blob/a5dba7d5e4a93c4d1b7020d5d789e0dfd3f4d30f/src/messages.rs#L50) function, here's an example of the current text message:

```
🧌 Order Id: 0c0e9936-4c21-47a5-87c1-01503a313003

        Your sale of sats has been completed after confirming payment from npub1kk30z9gus7xk3kf3m8zxh9paw4ngw023he9037y2jd7y7msfvvdskj8e60 ⚡️🍊⚡️
```

The proposed JSON payload for this one involves the creation of a new action, here called `SaleCompleted`. Here's an example:

```json
{
  "version": 0,
  "action": "SaleCompleted",
  "order_id": "6d3249ba-e5ec-4b7b-afa2-7d9b2ccab0dc",
  "content": {
    "Peer": {
        "pubkey": "npub1kk30z9gus7xk3kf3m8zxh9paw4ngw023he9037y2jd7y7msfvvdskj8e60",
    }
  }
}
```

**Comment by grunch** [comment]
in order to have messages for all different variants we will need to create a lot of new `Struct`s which I don't like much, how about this:

In cases like InvoiceAccepted action, instead of create a new struct with those 5 properties, what about sending the whole NewOrder struct? the client will receive data that don't need, but it can use the fields they need

it will be redundancy but we don't need to create many different structs that problably we will use only for one message

we can add buyer_pubkey and seller_pubkey in NewOrder

https://docs.rs/mostro-core/0.1.1/mostro_core/order/struct.NewOrder.html

For the other cases, FiatSent and SaleCompleted and more cases like this, we can create a struct that have a pubkey field, we know already that Struct will be used at least two times (FiatSend and SaleCompleted)

**Comment by grunch** [comment]
closing this issue via #5 and #6
