### ISSUE TITLE
Move certain reasons from "Actions" to "CantDoReason"

### ISSUE THREAD

**Issue by Catrya** [MostroP2P/mostro-core#77]
I was thinking we could take advantage of the existing CantDoReason and move some reasons currently in Actions over there. They all explain why something can't be done, so it would make more sense to unify them.
Reasons I suggest moving:
```
    IsNotYourOrder
    NotAllowedByStatus
    OutOfRangeFiatAmount
    IsNotYourDispute
    NotFound
    IncorrectInvoiceAmount
    InvalidSatsAmount
    OutOfRangeSatsAmount
```

**Comment by grunch** [comment]
closing via #78
